<?php
$blockIdToTexture = [
    1 => [
        0 => "stone",
        1 => "stone_granite",
        2 => "stone_granite_smooth",
        3 => "stone_diorite",
        4 => "stone_diorite_smooth",
        5 => "stone_andesite",
        6 => "stone_andesite_smooth",
    ],
    2 => "grass",
    3 => [
        0 => "dirt",
        1 => "coarse_dirt",
        2 => [
            "side" => "dirt_podzol_side",
            "top" => "dirt_podzol_top",
        ],
    ],
    4 => "cobblestone",
    5 => [
        0 => "planks_oak",
        1 => "planks_spruce",
        2 => "planks_birch",
        3 => "planks_jungle",
        4 => "planks_acacia",
        5 => "planks_big_oak",
    ],
    6 => [
        0 => "sapling_oak",
        1 => "sapling_spruce",
        2 => "sapling_birch",
        3 => "sapling_jungle",
        4 => "sapling_acacia",
        5 => "sapling_roofed_oak",
    ],
    7 => "bedrock",
    8 => "water_flow",
    9 => "water_still",
    10 => "lava_flow",
    11 => "lava_still",
    12 => [
        0 => "sand",
        1 => "red_sand",
    ],
    13 => "gravel",
    14 => "gold_ore",
    15 => "iron_ore",
    16 => "coal_ore",
    17 => [
        0 => [
            "side" => "log_oak",
            "top" => "log_oak_top",
        ],
        1 => [
            "side" => "log_spruce",
            "top" => "log_spruce_top",
        ],
        2 => [
            "side" => "log_birch",
            "top" => "log_birch_top",
        ],
        3 => [
            "side" => "log_jungle",
            "top" => "log_jungle_top",
        ],
    ],
    18 => [
        0 => "leaves_oak",
        1 => "leaves_spruce",
        2 => "leaves_birch",
        3 => "leaves_jungle",
    ],
    19 => [
        0 => "sponge",
        1 => "sponge_wet",
    ],
    20 => "glass",
    21 => "lapis_ore",
    23 => [
        0 => [
            "bottom" => "dispenser_front_vertical",
            "side" => "furnace_side",
        ],
        1 => [
            "top" => "dispenser_front_vertical",
            "side" => "furnace_side",
        ],
        2 => [
            "north" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        3 => [
            "south" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        4 => [
            "west" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        5 => [
            "east" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        8 => [
            "bottom" => "dispenser_front_vertical",
            "side" => "furnace_side",
        ],
        9 => [
            "top" => "dispenser_front_vertical",
            "side" => "furnace_side",
        ],
        10 => [
            "north" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        11 => [
            "south" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        12 => [
            "west" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ],
        13 => [
            "east" => "dispenser_front_horizontal",
            "side" => "furnace_side",
        ]
    ],
    24 => [
        0 => [
            "top" => "sandstone_top",
            "bottom" => "sandstone_bottom",
            "side" => "sandstone_normal",
        ],
        1 => [
            "top" => "sandstone_top",
            "bottom" => "sandstone_bottom",
            "side" => "sandstone_carved",
        ],
        2 => [
            "top" => "sandstone_top",
            "bottom" => "sandstone_bottom",
            "side" => "sandstone_smooth",
        ]
    ],
    25 => "noteblock",
    26 => [
        0 => [
            "end" => "bed_feet_end",
            "side" => "bed_feet_side",
            "top" => "bed_feet_top"
        ],
        1 => [
            "end" => "bed_feet_end",
            "side" => "bed_feet_side",
            "top" => "bed_feet_top"
        ],
        2 => [
            "end" => "bed_feet_end",
            "side" => "bed_feet_side",
            "top" => "bed_feet_top"
        ],
        3 => [
            "end" => "bed_feet_end",
            "side" => "bed_feet_side",
            "top" => "bed_feet_top"
        ],
        8 => [
            "end" => "bed_head_end",
            "side" => "bed_head_side",
            "top" => "bed_head_top"
        ],
        9 => [
            "end" => "bed_head_end",
            "side" => "bed_head_side",
            "top" => "bed_head_top"
        ],
        10 => [
            "end" => "bed_head_end",
            "side" => "bed_head_side",
            "top" => "bed_head_top"
        ],
        11 => [
            "end" => "bed_head_end",
            "side" => "bed_head_side",
            "top" => "bed_head_top"
        ]

    ],
    27 => "rail_golden_powered",
    28 => "rail_detector",
    29 => [
        "top" => "piston_top_sticky",
        "side" => "piston_side",
        "bottom" => "piston_bottom",
        "inner" => "piston_inner"
    ],
    30 => "cobweb",
    31 => [
        0 => "deadbush",
        1 => "tallgrass",
        2 => "fern",
    ],
    32 => "deadbush",
    33 => [
        "top" => "piston_top",
        "side" => "piston_side",
        "bottom" => "piston_bottom",
        "inner" => "piston_inner"
    ],
    34 => "piston_top",
    35 => [
        0 => "wool_colored_white",
        1 => "wool_colored_orange",
        2 => "wool_colored_magenta",
        3 => "wool_colored_light_blue",
        4 => "wool_colored_yellow",
        5 => "wool_colored_lime",
        6 => "wool_colored_pink",
        7 => "wool_colored_gray",
        8 => "wool_colored_light_gray",
        9 => "wool_colored_cyan",
        10 => "wool_colored_purple",
        11 => "wool_colored_blue",
        12 => "wool_colored_brown",
        13 => "wool_colored_green",
        14 => "wool_colored_red",
        15 => "wool_colored_black",
    ],
    37 => "flower_dandelion",
    38 => [
        0 => "flower_rose",
        1 => "flower_blue_orchid",
        2 => "flower_allium",
        3 => "flower_houstania",
        4 => "flower_tulip_red",
        5 => "flower_tulip_orange",
        6 => "flower_tulip_white",
        7 => "flower_tulip_pink",
        8 => "flower_oxeye_daisy",
    ],
    39 => "mushroom_brown",
    40 => "mushroom_red",
    41 => "gold_block",
    42 => "iron_block",
    43 => [
        0 => [
            "side" => "stone_slab_side",
            "top" => "stone_slab_top"
        ],
        1 => "sandstone_normal",
        2 => "planks_oak",
        3 => "cobblestone",
        4 => "brick",
        5 => "stonebrick",
        6 => "nether_brick",
        7 => "quartz_block_side",
    ],
    44 => [
        0 => "stone_slab_top",
        1 => "sandstone_normal",
        2 => "planks_oak",
        3 => "cobblestone",
        4 => "brick",
        5 => "stonebrick",
        6 => "nether_brick",
        7 => "quartz_block_side",
    ],
    45 => "brick",
    46 => [
        "top" => "tnt_top",
        "side" => "tnt_side",
        "bottom" => "tnt_bottom",
    ],
    47 => [
        "top" => "planks_oak",
        "sides" => "bookshelf",
    ],
    48 => "cobblestone_mossy",
    49 => "obsidian",
    50 => "torch",
    51 => "fire",
    52 => "mob_spawner",
    53 => "planks_oak",
    54 => "chest",
    55 => "redstone_dust_line1",
    56 => "diamond_ore",
    57 => "diamond_block",
    58 => [
        "top" => "crafting_table_top",
        "side" => "crafting_table_side",
        "bottom" => "planks_oak"
    ],
    59 => "wheat_stage_7",
    60 => [
        "top" => "farmland_wet",
        "side" => "dirt",
    ],
    61 => [
        "top" => "furnace_top",
        "side" => "furnace_side",
        "front" => "furnace_front",
    ],
    62 => [
        "top" => "furnace_top",
        "side" => "furnace_side",
        "front" => "furnace_front_on",
    ],
    63 => "sign",
    64 => [
        0 => "door_wood_lower",
        1 => "door_wood_lower",
        2 => "door_wood_lower",
        3 => "door_wood_lower",
        4 => "door_wood_lower",
        5 => "door_wood_lower",
        6 => "door_wood_lower",
        7 => "door_wood_lower",
        8 => "door_wood_upper",
        9 => "door_wood_upper",
        10 => "door_wood_upper",
        11 => "door_wood_upper",
        12 => "door_wood_upper",
        13 => "door_wood_upper",
        14 => "door_wood_upper",
        15 => "door_wood_upper",
    ],
    65 => "ladder",
    66 => "rail_normal",
    67 => "cobblestone",
    68 => "sign",
    69 => "lever",
    70 => "stone",
    71 => [
        0 => "door_iron_lower",
        1 => "door_iron_lower",
        2 => "door_iron_lower",
        3 => "door_iron_lower",
        4 => "door_iron_lower",
        5 => "door_iron_lower",
        6 => "door_iron_lower",
        7 => "door_iron_lower",
        8 => "door_iron_upper",
    ],
    72 => "planks_oak",
    73 => "redstone_ore",
    74 => "redstone_ore",
    75 => "redstone_torch_off",
    76 => "redstone_torch_on",
    77 => "stone",
    78 => "snow",
    79 => "ice",
    80 => "snow",
    81 => "cactus",
    82 => "clay",
    83 => "reeds",
    84 => [
        "top" => "jukebox",
        "side" => "noteblock",
    ],
    85 => "planks_oak",
    86 => "pumpkin_side",
    87 => "netherrack",
    88 => "soul_sand",
    89 => "glowstone",
    90 => "portal",
    91 => "pumpkin_side",
    92 => [
        "top" => "cake_top",
        "side" => "cake_side",
        "bottom" => "cake_bottom"
    ],
    93 => "repeater_off",
    94 => "repeater_on",
    95 => [
        0 => "glass_white",
        1 => "glass_orange",
        2 => "glass_magenta",
        3 => "glass_light_blue",
        4 => "glass_yellow",
        5 => "glass_lime",
        6 => "glass_pink",
        7 => "glass_gray",
        8 => "glass_light_gray",
        9 => "glass_cyan",
        10 => "glass_purple",
        11 => "glass_blue",
        12 => "glass_brown",
        13 => "glass_green",
        14 => "glass_red",
        15 => "glass_black",
    ],
    96 => "trapdoor",
    97 => [
        0 => "stone",
        1 => "cobblestone",
        2 => "stonebrick",
        3 => "stonebrick_mossy",
        4 => "stonebrick_cracked",
        5 => "stonebrick_carved",
    ],
    98 => [
        0 => "stonebrick",
        1 => "stonebrick_mossy",
        2 => "stonebrick_cracked",
        3 => "stonebrick_carved",
    ],
    99 => "mushroom_block_skin_brown",
    100 => "mushroom_block_skin_red",
    101 => "iron_bars",
    102 => "glass",
    103 => "melon_side",
    104 => "pumpkin_stem_disconnected",
    105 => "melon_stem_disconnected",
    106 => "vines",
    107 => "planks_oak",
    108 => "brick",
    109 => "stonebrick",
    110 => [
        "top" => "mycelium_side",
        "side" => "mycelium_top",
    ],
    111 => "waterlily",
    112 => "nether_brick",
    113 => "nether_brick",
    114 => "nether_brick",
    115 => "nether_wart_stage_2",
    116 => [
        "top" => "enchanting_table_top",
        "side" => "enchanting_table_side",
        "bottom" => "enchanting_table_bottom",
    ],
    117 => [
        "base" => "brewing_stand_base",
        "stand" => "brewing_stand",
    ],
    118 => [
        "top" => "cauldron_top",
        "side" => "cauldron_side",
        "inner" => "cauldron_inner",
        "bottom" => "cauldron_bottom",
    ],
    119 => "portal",
    120 => [
        "top" => "endframe_top",
        "side" => "endframe_side"
    ],
    121 => "end_stone",
    122 => "dragon_egg",
    123 => "redstone_lamp_off",
    124 => "redstone_lamp_on",
    125 => [
        0 => "planks_oak",
        1 => "planks_spruce",
        2 => "planks_birch",
        3 => "planks_jungle",
        4 => "planks_acacia",
        5 => "planks_big_oak",
    ],
    126 => [
        0 => "planks_oak",
        1 => "planks_spruce",
        2 => "planks_birch",
        3 => "planks_jungle",
        4 => "planks_acacia",
        5 => "planks_big_oak",
    ],
    127 => "cocoa_stage_2",
    128 => "sandstone_normal",
    129 => "emerald_ore",
    130 => "enderchest",
    131 => "trip_wire_source",
    132 => "trip_wire",
    133 => "emerald_block",
    134 => "planks_spruce",
    135 => "planks,birch",
    136 => "planks,jungle",
    137 => "command_block_side",
    138 => "beacon",
    139 => [
        0 => "cobblestone",
        1 => "cobblestone_mossy",
    ],
    140 => "flower_pot",
    141 => "carrots_stage_3",
    142 => "potatoes_stage_3",
    143 => "planks_oak",
    144 => null,
    145 => [
        "base" => "anvil_base",
        "top" => "anvil_top_damaged_0",
    ],
    146 => null,
    147 => "block_gold",
    148 => "block_iron",
    149 => "comparator_off",
    150 => "comparator_on",
    151 => [
        "top" => "daylight_detector_top",
        "side" => "daylight_detector_side"
    ],
    152 => "redstone_block",
    153 => "quartz_ore",
    154 => [
        "top" => "hopper_top",
        "outside" => "hopper_outside",
        "inside" => "hopper_inside",
    ],
    155 => [
        0 => [
            "top" => "quartz_block_top",
            "side" => "quartz_block_side",
            "bottom" => "quartz_block_bottom"
        ],
        1 => [
            "top" => "quartz_block_chiseled_top",
            "side" => "quartz_block_chiseled",
            "bottom" => "quartz_block_chiseled_top",
        ],
        2 => [
            "top" => "quartz_block_lines_top",
            "side" => "quartz_block_lines",
            "bottom" => "quartz_block_lines_top"
        ]
    ],
    156 => "quartz_block_side",
    157 => "rail_activator",
    158 => [
        0 => [
            "bottom" => "dropper_front_vertical",
            "side" => "furnace_side",
        ],
        1 => [
            "top" => "dropper_front_vertical",
            "side" => "furnace_side",
        ],
        2 => [
            "north" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        3 => [
            "south" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        4 => [
            "west" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        5 => [
            "east" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        8 => [
            "bottom" => "dropper_front_vertical",
            "side" => "furnace_side",
        ],
        9 => [
            "top" => "dropper_front_vertical",
            "side" => "furnace_side",
        ],
        10 => [
            "north" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        11 => [
            "south" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        12 => [
            "west" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ],
        13 => [
            "east" => "dropper_front_horizontal",
            "side" => "furnace_side",
        ]
    ],
    159 => [
        0 => "hardened_clay_stained_white",
        1 => "hardened_clay_stained_orange",
        2 => "hardened_clay_stained_magenta",
        3 => "hardened_clay_stained_light_blue",
        4 => "hardened_clay_stained_yellow",
        5 => "hardened_clay_stained_lime",
        6 => "hardened_clay_stained_pink",
        7 => "hardened_clay_stained_gray",
        8 => "hardened_clay_stained_light_gray",
        9 => "hardened_clay_stained_cyan",
        10 => "hardened_clay_stained_purple",
        11 => "hardened_clay_stained_blue",
        12 => "hardened_clay_stained_brown",
        13 => "hardened_clay_stained_green",
        14 => "hardened_clay_stained_red",
        15 => "hardened_clay_stained_black",
    ],
    160 => [
        0 => "glass_white",
        1 => "glass_orange",
        2 => "glass_magenta",
        3 => "glass_light_blue",
        4 => "glass_yellow",
        5 => "glass_lime",
        6 => "glass_pink",
        7 => "glass_gray",
        8 => "glass_light_gray",
        9 => "glass_cyan",
        10 => "glass_purple",
        11 => "glass_blue",
        12 => "glass_brown",
        13 => "glass_green",
        14 => "glass_red",
        15 => "glass_black",
    ],
    161 => "leaves_acacia",
    162 => [
        0 => [
            "top" => "log_acacia_top",
            "side" => "log_acacia_side",
        ],
        1 => [
            "top" => "log_big_oak_top",
            "side" => "log_big_oak_side",
        ],
    ],
    163 => "planks_acacia",
    164 => "planks_big_oak",
    165 => "slime",
    166 => null,
    167 => "trapdoor_iron",
    168 => [
        0 => "prismarine_rough",
        1 => "prismarine_bricks",
        2 => "prismarine_dark",
    ],
    169 => "sea_lantern",
    170 => [
        "top" => "hay_block_top",
        "side" => "hay_block_side",
    ],
    171 => [
        0 => "wool_colored_white",
        1 => "wool_colored_orange",
        2 => "wool_colored_magenta",
        3 => "wool_colored_light_blue",
        4 => "wool_colored_yellow",
        5 => "wool_colored_lime",
        6 => "wool_colored_pink",
        7 => "wool_colored_gray",
        8 => "wool_colored_light_gray",
        9 => "wool_colored_cyan",
        10 => "wool_colored_purple",
        11 => "wool_colored_blue",
        12 => "wool_colored_brown",
        13 => "wool_colored_green",
        14 => "wool_colored_red",
        15 => "wool_colored_black",
    ],
    172 => "hardened_clay",
    173 => "coal_block",
    174 => "ice_packed",
    175 => [
        0 => "double_plant_sunflower_bottom",
        1 => "double_plant_syringia_bottom",
        2 => "double_plant_grass_bottom",
        3 => "double_plant_fern_bottom",
        4 => "double_plant_rose_bottom",
        5 => "double_plant_paeonia_bottom",
        8 => "double_plant_sunflower_top",
        9 => "double_plant_syringia_top",
        10 => "double_plant_grass_top",
        11 => "double_plant_rose_top",
        12 => "double_plant_paonia_top"
    ],
    176 => "wool_colored_white",
    177 => "wool_colored_white",
    178 => [
        "top" => "daylight_detector_inverted_top",
        "side" => "daylight_detector_side"
    ],
    179 => [
        0 => [
            "top" => "red_sandstone_top",
            "bottom" => "red_sandstone_bottom",
            "side" => "red_sandstone_normal",
        ],
        1 => [
            "top" => "red_sandstone_top",
            "bottom" => "red_sandstone_bottom",
            "side" => "red_sandstone_carved",
        ],
        2 => [
            "top" => "red_sandstone_top",
            "bottom" => "red_sandstone_bottom",
            "side" => "red_sandstone_smooth",
        ]
    ],
    180 => "red_sandstone_normal",
    181 => "red_sandstone_normal",
    182 => "red_sandstone_normal",
    183 => "planks_spruce",
    184 => "planks_birch",
    185 => "planks_jungle",
    186 => "planks_big_oak",
    187 => "planks_acacia",
    188 => "planks_spruce",
    189 => "planks_birch",
    190 => "planks_jungle",
    191 => "planks_big_oak",
    192 => "planks_acacia",
    193 => [
        0 => "door_spruce_lower",
        1 => "door_spruce_lower",
        2 => "door_spruce_lower",
        3 => "door_spruce_lower",
        4 => "door_spruce_lower",
        5 => "door_spruce_lower",
        6 => "door_spruce_lower",
        7 => "door_spruce_lower",
        8 => "door_spruce_upper",
        9 => "door_spruce_upper",
        10 => "door_spruce_upper",
        11 => "door_spruce_upper",
        12 => "door_spruce_upper",
        13 => "door_spruce_upper",
        14 => "door_spruce_upper",
        15 => "door_spruce_upper",
    ],
    194 => [
        0 => "door_birch_lower",
        1 => "door_birch_lower",
        2 => "door_birch_lower",
        3 => "door_birch_lower",
        4 => "door_birch_lower",
        5 => "door_birch_lower",
        6 => "door_birch_lower",
        7 => "door_birch_lower",
        8 => "door_birch_upper",
        9 => "door_birch_upper",
        10 => "door_birch_upper",
        11 => "door_birch_upper",
        12 => "door_birch_upper",
        13 => "door_birch_upper",
        14 => "door_birch_upper",
        15 => "door_birch_upper",
    ],
    195 => [
        0 => "door_jungle_lower",
        1 => "door_jungle_lower",
        2 => "door_jungle_lower",
        3 => "door_jungle_lower",
        4 => "door_jungle_lower",
        5 => "door_jungle_lower",
        6 => "door_jungle_lower",
        7 => "door_jungle_lower",
        8 => "door_jungle_upper",
        9 => "door_jungle_upper",
        10 => "door_jungle_upper",
        11 => "door_jungle_upper",
        12 => "door_jungle_upper",
        13 => "door_jungle_upper",
        14 => "door_jungle_upper",
        15 => "door_jungle_upper",
    ],
    196 => [
        0 => "door_acacia_lower",
        1 => "door_acacia_lower",
        2 => "door_acacia_lower",
        3 => "door_acacia_lower",
        4 => "door_acacia_lower",
        5 => "door_acacia_lower",
        6 => "door_acacia_lower",
        7 => "door_acacia_lower",
        8 => "door_acacia_upper",
        9 => "door_acacia_upper",
        10 => "door_acacia_upper",
        11 => "door_acacia_upper",
        12 => "door_acacia_upper",
        13 => "door_acacia_upper",
        14 => "door_acacia_upper",
        15 => "door_acacia_upper",
    ],
    197 => [
        0 => "door_dark_oak_lower",
        1 => "door_dark_oak_lower",
        2 => "door_dark_oak_lower",
        3 => "door_dark_oak_lower",
        4 => "door_dark_oak_lower",
        5 => "door_dark_oak_lower",
        6 => "door_dark_oak_lower",
        7 => "door_dark_oak_lower",
        8 => "door_dark_oak_upper",
        9 => "door_dark_oak_upper",
        10 => "door_dark_oak_upper",
        11 => "door_dark_oak_upper",
        12 => "door_dark_oak_upper",
        13 => "door_dark_oak_upper",
        14 => "door_dark_oak_upper",
        15 => "door_dark_oak_upper",
    ],
    198 => "end_rod",
    199 => "chorus_plant",
    200 => "chorus_flower",
    201 => "purpur_block",
    202 => [
        "top" => "purpur_pillar_top",
        "side" => "purpur_pillar"
    ],
    203 => "purpur_block",
    204 => "purpur_block",
    205 => "purpur_block",
    206 => "end_bricks",
    208 => "grass_path_top",
    209 => null,
    210 => "repeating_command_block_back",
    211 => "chain_command_block_back",
    212 => "frosted_ice_1",
    213 => "magma",
    214 => "nether_wart_block",
    215 => "red_nether_brick",
    216 => "bone_block_side",
];