<?php
$blockIdToDataValues = [
    17 => [
        0 => [0 => 'variant:oak', 1 => 'axis:x',],
        1 => [0 => 'variant:spruce', 1 => 'axis:x',],
        2 => [0 => 'variant:birch', 1 => 'axis:x',],
        3 => [0 => 'variant:jungle', 1 => 'axis:x',],
        4 => [0 => 'variant:oak', 1 => 'axis:y',],
        5 => [0 => 'variant:spruce', 1 => 'axis:y',],
        6 => [0 => 'variant:birch', 1 => 'axis:y',],
        7 => [0 => 'variant:jungle', 1 => 'axis:y',],
        8 => [0 => 'variant:oak', 1 => 'axis:z',],
        9 => [0 => 'variant:spruce', 1 => 'axis:z',],
        10 => [0 => 'variant:birch', 1 => 'axis:z',],
        11 => [0 => 'variant:jungle', 1 => 'axis:z',],
        12 => [0 => 'variant:oak', 1 => 'axis:none',],
        13 => [0 => 'variant:spruce', 1 => 'axis:none',],
        14 => [0 => 'variant:birch', 1 => 'axis:none',],
        15 => [0 => 'variant:jungle', 1 => 'axis:none',],
    ],
    162 => [
        0 => [0 => 'variant:acacia', 1 => 'axis:z',],
        1 => [0 => 'variant:dark_oak', 1 => 'axis:z',],
        4 => [0 => 'variant:acacia', 1 => 'axis:x',],
        5 => [0 => 'variant:dark_oak', 1 => 'axis:x',],
        8 => [0 => 'variant:acacia', 1 => 'axis:y',],
        9 => [0 => 'variant:dark_oak', 1 => 'axis:y',],
        12 => [0 => 'variant:acacia', 1 => 'axis:none',],
        13 => [0 => 'variant:dark_oak', 1 => 'axis:none',],
    ],
    65 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    66 => [
        0 => [0 => 'shape:north_south',],
        1 => [0 => 'shape:east_west',],
        2 => [0 => 'shape:north_east',],
        3 => [0 => 'shape:north_west',],
        4 => [0 => 'shape:south_east',],
        5 => [0 => 'shape:south_west',],
        6 => [0 => 'shape:ascending_north',],
        7 => [0 => 'shape:ascending_south',],
        8 => [0 => 'shape:ascending_east',],
        9 => [0 => 'shape:ascending_west',],
    ],
    35 => [
        0 => [0 => 'color:white',],
        1 => [0 => 'color:orange',],
        2 => [0 => 'color:magenta',],
        3 => [0 => 'color:lightBlue',],
        4 => [0 => 'color:yellow',],
        5 => [0 => 'color:lime',],
        6 => [0 => 'color:pink',],
        7 => [0 => 'color:gray',],
        8 => [0 => 'color:silver',],
        9 => [0 => 'color:cyan',],
        10 => [0 => 'color:purple',],
        11 => [0 => 'color:blue',],
        12 => [0 => 'color:brown',],
        13 => [0 => 'color:green',],
        14 => [0 => 'color:red',],
        15 => [0 => 'color:black',],
    ],
    145 => [
        0 => [0 => 'damage:0', 1 => 'facing:north',],
        1 => [0 => 'damage:1', 1 => 'facing:east',],
        2 => [0 => 'damage:2', 1 => 'facing:south',],
        3 => [0 => 'damage:3', 1 => 'facing:west',],
        4 => [0 => 'damage:4', 1 => 'facing:north',],
        5 => [0 => 'damage:5', 1 => 'facing:east',],
        6 => [0 => 'damage:6', 1 => 'facing:south',],
        7 => [0 => 'damage:7', 1 => 'facing:west',],
        8 => [0 => 'damage:8', 1 => 'facing:north',],
        9 => [0 => 'damage:9', 1 => 'facing:east',],
        10 => [0 => 'damage:10', 1 => 'facing:south',],
        11 => [0 => 'damage:11', 1 => 'facing:west',],
    ],
    176 => [
        0 => [0 => 'rotation:south',],
        1 => [0 => 'rotation:south-southwest',],
        2 => [0 => 'rotation:southwest',],
        3 => [0 => 'rotation:west-southwest',],
        4 => [0 => 'rotation:west',],
        5 => [0 => 'rotation:west-northwest',],
        6 => [0 => 'rotation:northwest',],
        7 => [0 => 'rotation:north-northwest',],
        8 => [0 => 'rotation:north',],
        9 => [0 => 'rotation:north-northeast',],
        10 => [0 => 'rotation:northeast',],
        11 => [0 => 'rotation:east-northeast',],
        12 => [0 => 'rotation:east',],
        13 => [0 => 'rotation:east-southeast',],
        14 => [0 => 'rotation:southeast',],
        15 => [0 => 'rotation:south-southeast',],
    ],
    177 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:east',],
        5 => [0 => 'facing:west',],
    ],
    434 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
    ],
    216 => [0 => [0 => 'axis:y',], 4 => [0 => 'axis:x',], 8 => [0 => 'axis:z',],],
    26 => [
        0 => [0 => 'facing:south', 1 => 'occupied:false', 2 => 'part:foot',],
        1 => [0 => 'facing:west', 1 => 'occupied:false', 2 => 'part:foot',],
        2 => [0 => 'facing:north', 1 => 'occupied:false', 2 => 'part:foot',],
        3 => [0 => 'facing:east', 1 => 'occupied:false', 2 => 'part:foot',],
        8 => [0 => 'facing:south', 1 => 'occupied:false', 2 => 'part:head',],
        9 => [0 => 'facing:west', 1 => 'occupied:false', 2 => 'part:head',],
        10 => [0 => 'facing:north', 1 => 'occupied:false', 2 => 'part:head',],
        11 => [0 => 'facing:east', 1 => 'occupied:false', 2 => 'part:head',],
    ],
    117 => [
        0 => [0 => 'has_bottle_0:false', 1 => 'has_bottle_1:false', 2 => 'has_bottle_2:false',],
        1 => [0 => 'has_bottle_0:true', 1 => 'has_bottle_1:false', 2 => 'has_bottle_2:false',],
        2 => [0 => 'has_bottle_0:false', 1 => 'has_bottle_1:true', 2 => 'has_bottle_2:false',],
        3 => [0 => 'has_bottle_0:true', 1 => 'has_bottle_1:true', 2 => 'has_bottle_2:false',],
        4 => [0 => 'has_bottle_0:false', 1 => 'has_bottle_1:false', 2 => 'has_bottle_2:true',],
        5 => [0 => 'has_bottle_0:true', 1 => 'has_bottle_1:false', 2 => 'has_bottle_2:true',],
        6 => [0 => 'has_bottle_0:false', 1 => 'has_bottle_1:true', 2 => 'has_bottle_2:true',],
        7 => [0 => 'has_bottle_0:true', 1 => 'has_bottle_1:true', 2 => 'has_bottle_2:true',],
    ],
    77 => [
        0 => [0 => 'facing:down', 1 => 'powered:false',],
        1 => [0 => 'facing:east', 1 => 'powered:false',],
        2 => [0 => 'facing:west', 1 => 'powered:false',],
        3 => [0 => 'facing:south', 1 => 'powered:false',],
        4 => [0 => 'facing:north', 1 => 'powered:false',],
        5 => [0 => 'facing:up', 1 => 'powered:false',],
        8 => [0 => 'facing:down', 1 => 'powered:true',],
        9 => [0 => 'facing:east', 1 => 'powered:true',],
        10 => [0 => 'facing:west', 1 => 'powered:true',],
        11 => [0 => 'facing:south', 1 => 'powered:true',],
        12 => [0 => 'facing:north', 1 => 'powered:true',],
        13 => [0 => 'facing:up', 1 => 'powered:true',],
    ],
    81 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
        6 => [0 => 'age:6',],
        7 => [0 => 'age:7',],
        8 => [0 => 'age:8',],
        9 => [0 => 'age:9',],
        10 => [0 => 'age:10',],
        11 => [0 => 'age:11',],
        12 => [0 => 'age:12',],
        13 => [0 => 'age:13',],
        14 => [0 => 'age:14',],
        15 => [0 => 'age:15',],
    ],
    92 => [
        0 => [0 => 'bites:0',],
        1 => [0 => 'bites:1',],
        2 => [0 => 'bites:2',],
        3 => [0 => 'bites:3',],
        4 => [0 => 'bites:4',],
        5 => [0 => 'bites:5',],
        6 => [0 => 'bites:6',],
    ],
    171 => [
        0 => [0 => 'color:white',],
        1 => [0 => 'color:orange',],
        2 => [0 => 'color:magenta',],
        3 => [0 => 'color:lightBlue',],
        4 => [0 => 'color:yellow',],
        5 => [0 => 'color:lime',],
        6 => [0 => 'color:pink',],
        7 => [0 => 'color:gray',],
        8 => [0 => 'color:silver',],
        9 => [0 => 'color:cyan',],
        10 => [0 => 'color:purple',],
        11 => [0 => 'color:blue',],
        12 => [0 => 'color:brown',],
        13 => [0 => 'color:green',],
        14 => [0 => 'color:red',],
        15 => [0 => 'color:black',],
    ],
    141 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
        6 => [0 => 'age:6',],
        7 => [0 => 'age:7',],
    ],
    118 => [
        0 => [0 => 'level:0',],
        1 => [0 => 'level:1',],
        2 => [0 => 'level:2',],
        3 => [0 => 'level:3',],
    ],
    54 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    130 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    146 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    200 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
    ],
    199 => [
        0 => [
            0 => 'north:false',
            1 => 'south:false',
            2 => 'east:false',
            3 => 'west:false',
            4 => 'up:false',
            5 => 'down:false ',
        ],
    ],
    139 => [
        0 => [
            0 => 'north:false',
            1 => 'south:false',
            2 => 'east:false',
            3 => 'west:false',
            4 => 'up:true',
            5 => 'variant:cobblestone ',
        ],
        1 => [
            0 => 'north:false',
            1 => 'south:false',
            2 => 'east:false',
            3 => 'west:false',
            4 => 'up:true',
            5 => 'variant:mossy_cobblestone ',
        ],
    ],
    127 => [
        0 => [0 => 'facing:south', 1 => 'age:0',],
        1 => [0 => 'facing:west', 1 => 'age:0',],
        2 => [0 => 'facing:north', 1 => 'age:0',],
        3 => [0 => 'facing:east', 1 => 'age:0',],
        4 => [0 => 'facing:south', 1 => 'age:1',],
        5 => [0 => 'facing:west', 1 => 'age:1',],
        6 => [0 => 'facing:north', 1 => 'age:1',],
        7 => [0 => 'facing:east', 1 => 'age:1',],
        8 => [0 => 'facing:south', 1 => 'age:2',],
        9 => [0 => 'facing:west', 1 => 'age:2',],
        10 => [0 => 'facing:north', 1 => 'age:2',],
        11 => [0 => 'facing:east', 1 => 'age:2',],
    ],
    137 => [
        0 => [0 => 'conditional:false', 1 => 'facing:down',],
        1 => [0 => 'conditional:false', 1 => 'facing:up',],
        2 => [0 => 'conditional:false', 1 => 'facing:north',],
        3 => [0 => 'conditional:false', 1 => 'facing:south',],
        4 => [0 => 'conditional:false', 1 => 'facing:west',],
        5 => [0 => 'conditional:false', 1 => 'facing:east',],
        8 => [0 => 'conditional:true', 1 => 'facing:down',],
        9 => [0 => 'conditional:true', 1 => 'facing:up',],
        10 => [0 => 'conditional:true', 1 => 'facing:north',],
        11 => [0 => 'conditional:true', 1 => 'facing:south',],
        12 => [0 => 'conditional:true', 1 => 'facing:west',],
        13 => [0 => 'conditional:true', 1 => 'facing:east',],
    ],
    210 => [
        0 => [0 => 'conditional:false', 1 => 'facing:down',],
        1 => [0 => 'conditional:false', 1 => 'facing:up',],
        2 => [0 => 'conditional:false', 1 => 'facing:north',],
        3 => [0 => 'conditional:false', 1 => 'facing:south',],
        4 => [0 => 'conditional:false', 1 => 'facing:west',],
        5 => [0 => 'conditional:false', 1 => 'facing:east',],
        8 => [0 => 'conditional:true', 1 => 'facing:down',],
        9 => [0 => 'conditional:true', 1 => 'facing:up',],
        10 => [0 => 'conditional:true', 1 => 'facing:north',],
        11 => [0 => 'conditional:true', 1 => 'facing:south',],
        12 => [0 => 'conditional:true', 1 => 'facing:west',],
        13 => [0 => 'conditional:true', 1 => 'facing:east',],
    ],
    211 => [
        0 => [0 => 'conditional:false', 1 => 'facing:down',],
        1 => [0 => 'conditional:false', 1 => 'facing:up',],
        2 => [0 => 'conditional:false', 1 => 'facing:north',],
        3 => [0 => 'conditional:false', 1 => 'facing:south',],
        4 => [0 => 'conditional:false', 1 => 'facing:west',],
        5 => [0 => 'conditional:false', 1 => 'facing:east',],
        8 => [0 => 'conditional:true', 1 => 'facing:down',],
        9 => [0 => 'conditional:true', 1 => 'facing:up',],
        10 => [0 => 'conditional:true', 1 => 'facing:north',],
        11 => [0 => 'conditional:true', 1 => 'facing:south',],
        12 => [0 => 'conditional:true', 1 => 'facing:west',],
        13 => [0 => 'conditional:true', 1 => 'facing:east',],
    ],
    151 => [
        0 => [0 => 'power:0',],
        1 => [0 => 'power:1',],
        2 => [0 => 'power:2',],
        3 => [0 => 'power:3',],
        4 => [0 => 'power:4',],
        5 => [0 => 'power:5',],
        6 => [0 => 'power:6',],
        7 => [0 => 'power:7',],
        8 => [0 => 'power:8',],
        9 => [0 => 'power:9',],
        10 => [0 => 'power:10',],
        11 => [0 => 'power:11',],
        12 => [0 => 'power:12',],
        13 => [0 => 'power:13',],
        14 => [0 => 'power:14',],
        15 => [0 => 'power:15',],
    ],
    178 => [
        0 => [0 => 'power:0',],
        1 => [0 => 'power:1',],
        2 => [0 => 'power:2',],
        3 => [0 => 'power:3',],
        4 => [0 => 'power:4',],
        5 => [0 => 'power:5',],
        6 => [0 => 'power:6',],
        7 => [0 => 'power:7',],
        8 => [0 => 'power:8',],
        9 => [0 => 'power:9',],
        10 => [0 => 'power:10',],
        11 => [0 => 'power:11',],
        12 => [0 => 'power:12',],
        13 => [0 => 'power:13',],
        14 => [0 => 'power:14',],
        15 => [0 => 'power:15',],
    ],
    3 => [
        0 => [0 => 'snowy:false', 1 => 'variant:dirt',],
        1 => [0 => 'snowy:false', 1 => 'variant:coarse_dirt',],
        2 => [0 => 'snowy:false', 1 => 'variant:podzol',],
    ],
    23 => [
        0 => [0 => 'facing:down', 1 => 'triggered:false',],
        1 => [0 => 'facing:up', 1 => 'triggered:false',],
        2 => [0 => 'facing:north', 1 => 'triggered:false',],
        3 => [0 => 'facing:south', 1 => 'triggered:false',],
        4 => [0 => 'facing:west', 1 => 'triggered:false',],
        5 => [0 => 'facing:east', 1 => 'triggered:false',],
        8 => [0 => 'facing:down', 1 => 'triggered:true',],
        9 => [0 => 'facing:up', 1 => 'triggered:true',],
        10 => [0 => 'facing:north', 1 => 'triggered:true',],
        11 => [0 => 'facing:south', 1 => 'triggered:true',],
        12 => [0 => 'facing:west', 1 => 'triggered:true',],
        13 => [0 => 'facing:east', 1 => 'triggered:true',],
    ],
    64 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    193 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    194 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    195 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    196 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    197 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    71 => [
        0 => [
            0 => 'facing:east',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        1 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        2 => [
            0 => 'facing:west',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        3 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:false',
            4 => 'powered:false ',
        ],
        4 => [0 => 'facing:east', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        5 => [
            0 => 'facing:south',
            1 => 'half:lower',
            2 => 'highe:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        6 => [0 => 'facing:west', 1 => 'half:lower', 2 => 'hinge:right', 3 => 'open:true', 4 => 'powered:false',],
        7 => [
            0 => 'facing:north',
            1 => 'half:lower',
            2 => 'hinge:right',
            3 => 'open:true',
            4 => 'powered:false ',
        ],
        8 => [0 => 'facing:east', 1 => 'half:upper', 2 => 'hinge:left', 3 => 'open:false', 4 => 'powered:false',],
    ],
    158 => [
        0 => [0 => 'facing:down', 1 => 'triggered:false',],
        1 => [0 => 'facing:up', 1 => 'triggered:false',],
        2 => [0 => 'facing:north', 1 => 'triggered:false',],
        3 => [0 => 'facing:south', 1 => 'triggered:false',],
        4 => [0 => 'facing:west', 1 => 'triggered:false',],
        5 => [0 => 'facing:east', 1 => 'triggered:false',],
        8 => [0 => 'facing:down', 1 => 'triggered:true',],
        9 => [0 => 'facing:up', 1 => 'triggered:true',],
        10 => [0 => 'facing:north', 1 => 'triggered:true',],
        11 => [0 => 'facing:south', 1 => 'triggered:true',],
        12 => [0 => 'facing:west', 1 => 'triggered:true',],
        13 => [0 => 'facing:east', 1 => 'triggered:true',],
    ],
    120 => [
        0 => [0 => 'eye:false', 1 => 'facing:south',],
        1 => [0 => 'eye:false', 1 => 'facing:west',],
        2 => [0 => 'eye:false', 1 => 'facing:north',],
        3 => [0 => 'eye:false', 1 => 'facing:east',],
        4 => [0 => 'eye:true', 1 => 'facing:south',],
        5 => [0 => 'eye:true', 1 => 'facing:west',],
        6 => [0 => 'eye:true', 1 => 'facing:north',],
        7 => [0 => 'eye:true', 1 => 'facing:east',],
    ],
    198 => [
        0 => [0 => 'facing:down',],
        1 => [0 => 'facing:up',],
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    60 => [
        0 => [0 => 'moisture:0',],
        1 => [0 => 'moisture', 1 => '1',],
        2 => [0 => 'moisture', 1 => '2',],
        3 => [0 => 'moisture', 1 => '3',],
        4 => [0 => 'moisture', 1 => '4',],
        5 => [0 => 'moisture', 1 => '5',],
        6 => [0 => 'moisture', 1 => '6',],
        7 => [0 => 'moisture', 1 => '7',],
    ],
    85 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    188 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    189 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    190 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    191 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    192 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    113 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    107 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    183 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    184 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    185 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    186 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    187 => [
        0 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:false', 3 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'in_wall:false', 2 => 'open:true', 3 => 'powered:false',],
    ],
    51 => [
        0 => [
            0 => 'age:0',
            1 => 'up:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false ',
        ],
    ],
    37 => [0 => [0 => 'type:dandelion',],],
    38 => [
        0 => [0 => 'type:poppy',],
        1 => [0 => 'type:blue_orchard',],
        2 => [0 => 'type:allium',],
        3 => [0 => 'type:houstonia',],
        4 => [0 => 'type:red_tulip',],
        5 => [0 => 'type:orange_tulip',],
        6 => [0 => 'type:white_tulip',],
        7 => [0 => 'type:pink_tulip',],
        8 => [0 => 'type:oxeye_daisy',],
    ],
    175 => [
        0 => [0 => 'half:lower', 1 => 'variant:sunflower', 2 => 'facing:east',],
        1 => [0 => 'half:lower', 1 => 'variant:syringa', 2 => 'facing:east',],
        2 => [0 => 'half:lower', 1 => 'variant:double_grass', 2 => 'facing:east',],
        3 => [0 => 'half:lower', 1 => 'variant:double_fern', 2 => 'facing:east',],
        4 => [0 => 'half:lower', 1 => 'variant:double_rose', 2 => 'facing:east',],
        5 => [0 => 'half:lower', 1 => 'variant:paeonia', 2 => 'facing:east',],
        8 => [0 => 'half:upper', 1 => 'variant:sunflower', 2 => 'facing:north',],
    ],
    140 => [0 => [0 => 'contents:empty', 1 => 'legacy_data:0',],],
    212 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
    ],
    61 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    62 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        5 => [0 => 'facing:east',],
    ],
    63 => [
        4 => [0 => 'rotation:west',],
        0 => [0 => 'rotation:south',],
        1 => [0 => 'rotation:south-southwest',],
        2 => [0 => 'rotation:southwest',],
        3 => [0 => 'rotation:west-southwest',],
        5 => [0 => 'rotation:west-northwest',],
        6 => [0 => 'rotation:northwest',],
        7 => [0 => 'rotation:north-northwest',],
        8 => [0 => 'rotation:north',],
        9 => [0 => 'rotation:north-northeast',],
        10 => [0 => 'rotation:northeast',],
        11 => [0 => 'rotation:east-northeast',],
        12 => [0 => 'rotation:east',],
        13 => [0 => 'rotation:east-southeast',],
        14 => [0 => 'rotation:southeast',],
        15 => [0 => 'rotation:south-southeast',],
    ],
    102 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    160 => [
        0 => [
            0 => 'color:white',
            1 => 'north:false',
            2 => 'south:false',
            3 => 'east:false',
            4 => 'west:false ',
        ],
        1 => [0 => 'color:orange', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        2 => [
            0 => 'color:magenta',
            1 => 'north:false',
            2 => 'south:false',
            3 => 'east:false',
            4 => 'west:false ',
        ],
        3 => [
            0 => 'color:lightBlue',
            1 => 'north:false',
            2 => 'south:false',
            3 => 'east:false',
            4 => 'west:false ',
        ],
        4 => [0 => 'color:yellow', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        5 => [0 => 'color:lime', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        6 => [0 => 'color:pink', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        7 => [0 => 'color:gray', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        8 => [0 => 'color:silver', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        9 => [0 => 'color:cyan', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        10 => [
            0 => 'color:purple',
            1 => 'north:false',
            2 => 'south:false',
            3 => 'east:false',
            4 => 'west:false ',
        ],
        11 => [0 => 'color:blue', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        12 => [0 => 'color:brown', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        13 => [0 => 'color:green', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        14 => [0 => 'color:red', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
        15 => [0 => 'color:black', 1 => 'north:false', 2 => 'south:false', 3 => 'east:false', 4 => 'west:false',],
    ],
    31 => [
        0 => [0 => 'type:dead_bush',],
        1 => [0 => 'type:tall_grass',],
        2 => [0 => 'type:fern',],
    ],
    2 => [0 => [0 => 'snowy:false',],],
    170 => [0 => [0 => 'axis:x',], 4 => [0 => 'axis:y',], 8 => [0 => 'axis:z',],],
    154 => [
        0 => [0 => 'enabled:true', 1 => 'facing:down',],
        2 => [0 => 'enabled:true', 1 => 'facing:north',],
        3 => [0 => 'enabled:true', 1 => 'facing:south',],
        4 => [0 => 'enabled:true', 1 => 'facing:west',],
        5 => [0 => 'enabled:true', 1 => 'facing:east',],
    ],
    101 => [0 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false',],],
    91 => [
        0 => [0 => 'facing:south',],
        1 => [0 => 'facing:west',],
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:east',],
        4 => [0 => 'facing:south',],
    ],
    84 => [0 => [0 => 'has_record:false',], 1 => [0 => 'has_record:true',],],
    10 => [
        0 => [0 => 'level:0',],
        1 => [0 => 'level:1',],
        2 => [0 => 'level:2',],
        3 => [0 => 'level:3',],
        4 => [0 => 'level:4',],
        5 => [0 => 'level:5',],
        6 => [0 => 'level:6',],
        7 => [0 => 'level:7',],
        8 => [0 => 'level:8',],
        9 => [0 => 'level:9',],
        10 => [0 => 'level:10',],
        11 => [0 => 'level:11',],
        12 => [0 => 'level:12',],
        13 => [0 => 'level:13',],
        14 => [0 => 'level:14',],
        15 => [0 => 'level:15',],
    ],
    11 => [
        0 => [0 => 'level:0',],
        1 => [0 => 'level:1',],
        2 => [0 => 'level:2',],
        3 => [0 => 'level:3',],
        4 => [0 => 'level:4',],
        5 => [0 => 'level:5',],
        6 => [0 => 'level:6',],
        7 => [0 => 'level:7',],
        8 => [0 => 'level:8',],
        9 => [0 => 'level:9',],
        10 => [0 => 'level:10',],
        11 => [0 => 'level:11',],
        12 => [0 => 'level:12',],
        13 => [0 => 'level:13',],
        14 => [0 => 'level:14',],
        15 => [0 => 'level:15',],
    ],
    18 => [
        0 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:oak',],
        1 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:spruce',],
        2 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:birch',],
        3 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:jungle',],
        4 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:oak',],
        5 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:spruce',],
        6 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:birch',],
        7 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:jungle',],
        8 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:oak',],
        9 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:spruce',],
        10 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:birch',],
        11 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:jungle',],
        12 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:oak',],
        13 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:spruce',],
        14 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:birch',],
        15 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:jungle',],
    ],
    161 => [
        0 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:acacia',],
        1 => [0 => 'check_decay:false', 1 => 'decayable:true', 2 => 'variant:dark_oak',],
        4 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:acacia',],
        5 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:dark_oak',],
        8 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:acacia',],
        9 => [0 => 'check_decay:true', 1 => 'decayable:true', 2 => 'variant:dark_oak',],
        12 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:acacia',],
        13 => [0 => 'check_decay:false', 1 => 'decayable:false', 2 => 'variant:dark_oak',],
    ],
    69 => [
        0 => [0 => 'facing:down_x', 1 => 'powered:false',],
        1 => [0 => 'facing:east', 1 => 'powered:false',],
        2 => [0 => 'facing:west', 1 => 'powered:false',],
        3 => [0 => 'facing:south', 1 => 'powered:false',],
        4 => [0 => 'facing:north', 1 => 'powered:false',],
        5 => [0 => 'facing:up_z', 1 => 'powered:false',],
        6 => [0 => 'facing:up_x', 1 => 'powered:false',],
        7 => [0 => 'facing:down_z', 1 => 'powered:false',],
        8 => [0 => 'facing:down_x', 1 => 'powered:true',],
        9 => [0 => 'facing:east', 1 => 'powered:true',],
        10 => [0 => 'facing:west', 1 => 'powered:true',],
        11 => [0 => 'facing:south', 1 => 'powered:true',],
        12 => [0 => 'facing:north', 1 => 'powered:true',],
        13 => [0 => 'facing:up_z', 1 => 'powered:true',],
        14 => [0 => 'facing:up_x', 1 => 'powered:true',],
        15 => [0 => 'facing:down_z', 1 => 'powered:true',],
    ],
    105 => [
        0 => [0 => 'age:0', 1 => 'facing:up',],
        1 => [0 => 'age:1', 1 => 'facing:up',],
        2 => [0 => 'age:2', 1 => 'facing:up',],
        3 => [0 => 'age:3', 1 => 'facing:up',],
        4 => [0 => 'age:4', 1 => 'facing:up',],
        5 => [0 => 'age:5', 1 => 'facing:up',],
        6 => [0 => 'age:6', 1 => 'facing:up',],
        7 => [0 => 'age:7', 1 => 'facing:up',],
    ],
    97 => [
        0 => [0 => 'variant:stone',],
        1 => [0 => 'variant:cobblestonstone',],
        2 => [0 => 'variant:stone_brick',],
        3 => [0 => 'variant:mossy_brick',],
        4 => [0 => 'variant:cracked_brick',],
        5 => [0 => 'variant:chisled_brick',],
    ],
    99 => [
        0 => [0 => 'variant:east',],
        1 => [0 => 'variant:north',],
        2 => [0 => 'variant:north_east',],
        3 => [0 => 'variant:north_west',],
        4 => [0 => 'variant:south',],
        5 => [0 => 'variant:south_east',],
        6 => [0 => 'variant:south_west',],
        7 => [0 => 'variant:west',],
        8 => [0 => 'variant:center',],
        9 => [0 => 'variant:stem',],
        10 => [0 => 'variant:all_inside',],
        14 => [0 => 'variant:all_outside',],
        15 => [0 => 'variant:all_stem',],
    ],
    100 => [
        0 => [0 => 'variant:east',],
        1 => [0 => 'variant:north',],
        2 => [0 => 'variant:north_east',],
        3 => [0 => 'variant:north_west',],
        4 => [0 => 'variant:south',],
        5 => [0 => 'variant:south_east',],
        6 => [0 => 'variant:south_west',],
        7 => [0 => 'variant:west',],
        8 => [0 => 'variant:center',],
        9 => [0 => 'variant:stem',],
        10 => [0 => 'variant:all_inside',],
        14 => [0 => 'variant:all_outside',],
        15 => [0 => 'variant:all_stem',],
    ],
    115 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
    ],
    29 => [
        0 => [0 => 'extended:false', 1 => 'facing:down',],
        1 => [0 => 'extended:false', 1 => 'facing:up',],
        2 => [0 => 'extended:false', 1 => 'facing:north',],
        3 => [0 => 'extended:false', 1 => 'facing:south',],
        4 => [0 => 'extended:false', 1 => 'facing:west',],
        5 => [0 => 'extended:false', 1 => 'facing:east',],
    ],
    33 => [
        0 => [0 => 'extended:false', 1 => 'facing:down',],
        1 => [0 => 'extended:false', 1 => 'facing:up',],
        2 => [0 => 'extended:false', 1 => 'facing:north',],
        3 => [0 => 'extended:false', 1 => 'facing:south',],
        4 => [0 => 'extended:false', 1 => 'facing:west',],
        5 => [0 => 'extended:false', 1 => 'facing:east',],
    ],
    34 => [
        0 => [0 => 'facing:down', 1 => 'short:false', 2 => 'type:normal',],
        1 => [0 => 'facing:up', 1 => 'short:false', 2 => 'type:normal',],
        2 => [0 => 'facing:north', 1 => 'short:false', 2 => 'type:normal',],
        3 => [0 => 'facing:south', 1 => 'short:false', 2 => 'type:normal',],
        4 => [0 => 'facing:west', 1 => 'short:false', 2 => 'type:normal',],
        5 => [0 => 'facing:east', 1 => 'short:false', 2 => 'type:normal',],
    ],
    90 => [0 => [0 => 'axis:x',], 2 => [0 => 'axis:z',],],
    142 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
        6 => [0 => 'age:6',],
        7 => [0 => 'age:7',],
    ],
    70 => [0 => [0 => 'powered:false',], 1 => [0 => 'powered:true',],],
    72 => [1 => [0 => 'powered:true',],],
    168 => [
        0 => [0 => 'variant:prismarine',],
        1 => [0 => 'variant:prismarine_bricks',],
        2 => [0 => 'variant:dark_prismarine',],
    ],
    86 => [
        0 => [0 => 'facing:south',],
        1 => [0 => 'facing:west',],
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:east',],
        4 => [0 => 'facing:north',],
    ],
    104 => [
        0 => [0 => 'age:0', 1 => 'facing:up',],
        1 => [0 => 'age:1', 1 => 'facing:up',],
        2 => [0 => 'age:2', 1 => 'facing:up',],
        3 => [0 => 'age:3', 1 => 'facing:up',],
        4 => [0 => 'age:4', 1 => 'facing:up',],
        5 => [0 => 'age:5', 1 => 'facing:up',],
        6 => [0 => 'age:6', 1 => 'facing:up',],
        7 => [0 => 'age:7', 1 => 'facing:up',],
    ],
    202 => [0 => [0 => 'axis:7',], 4 => [0 => 'axis:x',], 8 => [0 => 'axis:z',],],
    155 => [
        0 => [0 => 'variant:default',],
        1 => [0 => 'variant:chisled',],
        2 => [0 => 'variant:lines_y',],
        3 => [0 => 'variant:lines_z',],
        4 => [0 => 'variant:lines_x',],
    ],
    157 => [
        0 => [0 => 'powered:false', 1 => 'shape:north_south',],
        1 => [0 => 'powered:false', 1 => 'shape:east_west',],
        2 => [0 => 'powered:false', 1 => 'shape:ascending_north',],
        3 => [0 => 'powered:false', 1 => 'shape:ascending_south',],
        4 => [0 => 'powered:false', 1 => 'shape:ascending_east',],
        5 => [0 => 'powered:false', 1 => 'shape:ascending_west',],
        8 => [0 => 'powered:true', 1 => 'shape:north_south',],
        9 => [0 => 'powered:true', 1 => 'shape:east_west',],
        10 => [0 => 'powered:true', 1 => 'shape:ascending_north',],
        11 => [0 => 'powered:true', 1 => 'shape:ascending_south',],
        12 => [0 => 'powered:true', 1 => 'shape:ascending_east',],
        13 => [0 => 'powered:true', 1 => 'shape:ascending_west',],
    ],
    28 => [
        0 => [0 => 'powered:false', 1 => 'shape:north_south',],
        1 => [0 => 'powered:false', 1 => 'shape:east_west',],
        2 => [0 => 'powered:false', 1 => 'shape:ascending_north',],
        3 => [0 => 'powered:false', 1 => 'shape:ascending_south',],
        4 => [0 => 'powered:false', 1 => 'shape:ascending_east',],
        5 => [0 => 'powered:false', 1 => 'shape:ascending_west',],
        8 => [0 => 'powered:true', 1 => 'shape:north_south',],
        9 => [0 => 'powered:true', 1 => 'shape:east_west',],
        10 => [0 => 'powered:true', 1 => 'shape:ascending_north',],
        11 => [0 => 'powered:true', 1 => 'shape:ascending_south',],
        12 => [0 => 'powered:true', 1 => 'shape:ascending_east',],
        13 => [0 => 'powered:true', 1 => 'shape:ascending_west',],
    ],
    27 => [
        0 => [0 => 'powered:false', 1 => 'shape:north_south',],
        1 => [0 => 'powered:false', 1 => 'shape:east_west',],
        2 => [0 => 'powered:false', 1 => 'shape:ascending_north',],
        3 => [0 => 'powered:false', 1 => 'shape:ascending_south',],
        4 => [0 => 'powered:false', 1 => 'shape:ascending_east',],
        5 => [0 => 'powered:false', 1 => 'shape:ascending_west',],
        8 => [0 => 'powered:true', 1 => 'shape:north_south',],
        9 => [0 => 'powered:true', 1 => 'shape:east_west',],
        10 => [0 => 'powered:true', 1 => 'shape:ascending_north',],
        11 => [0 => 'powered:true', 1 => 'shape:ascending_south',],
        12 => [0 => 'powered:true', 1 => 'shape:ascending_east',],
        13 => [0 => 'powered:true', 1 => 'shape:ascending_west',],
    ],
    24 => [
        0 => [0 => 'variant:sandstone',],
        1 => [0 => 'variant:chiseled_sandstone',],
        2 => [0 => 'variant:smooth_sandstone',],
    ],
    179 => [
        0 => [0 => 'variant:red_sandstone',],
        1 => [0 => 'variant:chiseled_red_sandstone',],
        2 => [0 => 'variant:smooth_red_sandstone',],
    ],
    149 => [
        0 => [0 => 'facing:south', 1 => 'mode:compact', 2 => 'powered:false',],
        1 => [0 => 'facing:west', 1 => 'mode:compact', 2 => 'powered:false',],
        2 => [0 => 'facing:north', 1 => 'mode:compact', 2 => 'powered:false',],
        3 => [0 => 'facing:east', 1 => 'mode:compact', 2 => 'powered:false',],
        4 => [0 => 'facing:south', 1 => 'mode:subtract', 2 => 'powered:false',],
        5 => [0 => 'facing:west', 1 => 'mode:subtract', 2 => 'powered:false',],
        6 => [0 => 'facing:north', 1 => 'mode:subtract', 2 => 'powered:false',],
        7 => [0 => 'facing:east', 1 => 'mode:subtract', 2 => 'powered:false',],
        8 => [0 => 'facing:south', 1 => 'mode:subtract', 2 => 'powered:true',],
        9 => [0 => 'facing:west', 1 => 'mode:subtract', 2 => 'powered:true',],
        10 => [0 => 'facing:north', 1 => 'mode:subtract', 2 => 'powered:true',],
        11 => [0 => 'facing:east', 1 => 'mode:subtract', 2 => 'powered:true',],
    ],
    55 => [
        0 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:0',],
        1 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:1',],
        2 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:2',],
        3 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:3',],
        4 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:4',],
        5 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:5',],
        6 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:6',],
        7 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:7',],
        8 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:8',],
        9 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:9',],
        10 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:10',],
        11 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:11',],
        12 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:12',],
        13 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:13',],
        14 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:14',],
        15 => [0 => 'north:none', 1 => 'south:none', 2 => 'east:none', 3 => 'west:none', 4 => 'power:15',],
    ],
    76 => [
        1 => [0 => 'facing:east',],
        2 => [0 => 'facing:west',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:north',],
        5 => [0 => 'facing:up',],
    ],
    75 => [
        1 => [0 => 'facing:east',],
        2 => [0 => 'facing:west',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:north',],
        5 => [0 => 'facing:up',],
    ],
    50 => [
        1 => [0 => 'facing:east',],
        2 => [0 => 'facing:west',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:north',],
        5 => [0 => 'facing:up',],
    ],
    12 => [0 => [0 => 'variant:sand',], 1 => [0 => 'variant:red_sand',],],
    6 => [
        0 => [0 => 'stage:0', 1 => 'type:oak',],
        1 => [0 => 'stage:0', 1 => 'type:spruce',],
        2 => [0 => 'stage:0', 1 => 'type:birch',],
        3 => [0 => 'stage:0', 1 => 'type:jungle',],
        4 => [0 => 'stage:0', 1 => 'type:acacia',],
        5 => [0 => 'stage:0', 1 => 'type:dark_oak',],
    ],
    68 => [
        2 => [0 => 'facing:north',],
        3 => [0 => 'facing:south',],
        4 => [0 => 'facing:west',],
        5 => [0 => 'facing:east',],
    ],
    144 => [
        1 => [0 => 'facing:up', 1 => 'nodrop:true',],
        2 => [0 => 'facing:north', 1 => 'nodrop:true',],
        3 => [0 => 'facing:south', 1 => 'nodrop:true',],
        4 => [0 => 'facing:east', 1 => 'nodrop:true',],
        5 => [0 => 'facing:west', 1 => 'nodrop:true',],
    ],
    43 => [
        0 => [0 => 'seamless:false', 1 => 'variant:stone',],
        1 => [0 => 'seamless:false', 1 => 'variant:sandstone',],
        2 => [0 => 'seamless:false', 1 => 'variant:wood_old',],
        3 => [0 => 'seamless:false', 1 => 'variant:cobblestone',],
        4 => [0 => 'seamless:false', 1 => 'variant:brick',],
        5 => [0 => 'seamless:false', 1 => 'variant:stone_brick',],
        6 => [0 => 'seamless:false', 1 => 'variant:nether_brick',],
        7 => [0 => 'seamless:false', 1 => 'variant:quartz',],
        8 => [0 => 'seamless:true', 1 => 'variant:stone',],
        9 => [0 => 'seamless:true', 1 => 'variant:sandstone',],
        15 => [0 => 'seamless:true', 1 => 'variant:quartz',],
    ],
    44 => [
        0 => [0 => 'half:bottom', 1 => 'variant:stone',],
        1 => [0 => 'half:bottom', 1 => 'variant:sandstone',],
        2 => [0 => 'half:bottom', 1 => 'variant:wood_old',],
        3 => [0 => 'half:bottom', 1 => 'variant:cobblestone',],
        4 => [0 => 'half:bottom', 1 => 'variant:brick',],
        5 => [0 => 'half:bottom', 1 => 'variant:stone_brick',],
        6 => [0 => 'half:bottom', 1 => 'variant:nether_brick',],
        7 => [0 => 'half:bottom', 1 => 'variant:quartz',],
        8 => [0 => 'half:top', 1 => 'variant:stone',],
        9 => [0 => 'half:top', 1 => 'variant:sandstone',],
        10 => [0 => 'half:top', 1 => 'variant:wood_old',],
        11 => [0 => 'half:top', 1 => 'variant:cobblestone',],
        12 => [0 => 'half:top', 1 => 'variant:brick',],
        13 => [0 => 'half:top', 1 => 'variant:stone_brick',],
        14 => [0 => 'half:top', 1 => 'variant:nether_brick',],
        15 => [0 => 'half:top', 1 => 'variant:quartz',],
    ],
    125 => [
        0 => [0 => 'variant:oak',],
        1 => [0 => 'variant:spruce',],
        2 => [0 => 'variant:birch',],
        3 => [0 => 'variant:jungle',],
        4 => [0 => 'variant:acacia',],
        5 => [0 => 'variant:dark_oak',],
    ],
    126 => [
        0 => [0 => 'half:bottom', 1 => 'variant:oak',],
        1 => [0 => 'half:bottom', 1 => 'variant:spruce',],
        2 => [0 => 'half:bottom', 1 => 'variant:birch',],
        3 => [0 => 'half:bottom', 1 => 'variant:jungle',],
        4 => [0 => 'half:bottom', 1 => 'variant:acacia',],
        5 => [0 => 'half:bottom', 1 => 'variant:dark_oak',],
        6 => [0 => 'half:top', 1 => 'variant:oak',],
        7 => [0 => 'half:top', 1 => 'variant:spruce',],
        8 => [0 => 'half:top', 1 => 'variant:birch',],
        9 => [0 => 'half:top', 1 => 'variant:jungle',],
        10 => [0 => 'half:top', 1 => 'variant:acacia',],
        11 => [0 => 'half:top', 1 => 'variant:dark_oak',],
    ],
    181 => [
        0 => [0 => 'seamless:false', 1 => 'variant:red_sandstone',],
        8 => [0 => 'seamless:true', 1 => 'variant:red_standstone',],
    ],
    182 => [
        0 => [0 => 'half:bottom', 1 => 'variant:red_sandstone',],
        8 => [0 => 'half:top', 1 => 'variant:red_sandstone',],
    ],
    204 => [0 => [0 => 'variant:default',],],
    205 => [
        0 => [0 => 'half:bottom', 1 => 'variant:default',],
        1 => [0 => 'half:top', 1 => 'variant:default',],
    ],
    78 => [
        0 => [0 => 'layers:1',],
        1 => [0 => 'layers:2',],
        2 => [0 => 'layers:3',],
        3 => [0 => 'layers:4',],
        4 => [0 => 'layers:5',],
        5 => [0 => 'layers:6',],
        6 => [0 => 'layers:7',],
        7 => [0 => 'layers:8',],
    ],
    19 => [0 => [0 => 'wet:false',], 1 => [0 => 'wet:true',],],
    159 => [
        0 => [0 => 'color:white',],
        1 => [0 => 'color:orange',],
        2 => [0 => 'color:magenta',],
        3 => [0 => 'color:lightBlue',],
        4 => [0 => 'color:yellow',],
        5 => [0 => 'color:lime',],
        6 => [0 => 'color:pink',],
        7 => [0 => 'color:gray',],
        8 => [0 => 'color:silver',],
        9 => [0 => 'color:cyan',],
        10 => [0 => 'color:purple',],
        11 => [0 => 'color:blue',],
        12 => [0 => 'color:brown',],
        13 => [0 => 'color:green',],
        14 => [0 => 'color:red',],
        15 => [0 => 'color:black',],
    ],
    95 => [
        0 => [0 => 'color:white',],
        1 => [0 => 'color:orange',],
        2 => [0 => 'color:magenta',],
        3 => [0 => 'color:lightBlue',],
        4 => [0 => 'color:yellow',],
        5 => [0 => 'color:lime',],
        6 => [0 => 'color:pink',],
        7 => [0 => 'color:gray',],
        8 => [0 => 'color:silver',],
        9 => [0 => 'color:cyan',],
        10 => [0 => 'color:purple',],
        11 => [0 => 'color:blue',],
        12 => [0 => 'color:brown',],
        13 => [0 => 'color:green',],
        14 => [0 => 'color:red',],
        15 => [0 => 'color:black',],
    ],
    53 => [
        0 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    67 => [
        0 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    108 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    109 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:sout', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    114 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    128 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    134 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    135 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    136 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    156 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    163 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    164 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    180 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    203 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'shape:straight',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'shape:straight',],
        2 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'shape:straight',],
        3 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'shape:straight',],
        4 => [0 => 'facing:north', 1 => 'half:top', 2 => 'shape:straight',],
        5 => [0 => 'facing:south', 1 => 'half:top', 2 => 'shape:straight',],
        6 => [0 => 'facing:east', 1 => 'half:top', 2 => 'shape:straight',],
        7 => [0 => 'facing:west', 1 => 'half:top', 2 => 'shape:straight',],
    ],
    98 => [
        0 => [0 => 'variant:stonebrick',],
        1 => [0 => 'variant:mossy_stonebrick',],
        2 => [0 => 'variant:cracked_stonebrick',],
        3 => [0 => 'variant:chisled_stonebrick',],
    ],
    83 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
        6 => [0 => 'age:6',],
        7 => [0 => 'age:7',],
        8 => [0 => 'age:8',],
        9 => [0 => 'age:9',],
        10 => [0 => 'age:10',],
        11 => [0 => 'age:11',],
        12 => [0 => 'age:12',],
        13 => [0 => 'age:13',],
        14 => [0 => 'age:14',],
        15 => [0 => 'age:15',],
    ],
    46 => [0 => [0 => 'explode:false',], 1 => [0 => 'explode:true',],],
    96 => [
        0 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'open:false',],
        1 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'open:false',],
        2 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'open:false',],
        3 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'open:false',],
        4 => [0 => 'facing:north', 1 => 'half:bottom', 2 => 'open:true',],
        5 => [0 => 'facing:south', 1 => 'half:bottom', 2 => 'open:true',],
        6 => [0 => 'facing:west', 1 => 'half:bottom', 2 => 'open:true',],
        7 => [0 => 'facing:east', 1 => 'half:bottom', 2 => 'open:true',],
        8 => [0 => 'facing:north', 1 => 'half:top', 2 => 'open:false',],
        9 => [0 => 'facing:south', 1 => 'half:top', 2 => 'open:false',],
        10 => [0 => 'facing:west', 1 => 'half:top', 2 => 'open:false',],
        11 => [0 => 'facing:east', 1 => 'half:top', 2 => 'open:false',],
        12 => [0 => 'facing:north', 1 => 'half:top', 2 => 'open:true',],
        13 => [0 => 'facing:south', 1 => 'half:top', 2 => 'open:true',],
        14 => [0 => 'facing:west', 1 => 'half:top', 2 => 'open:true',],
        15 => [0 => 'facing:east', 1 => 'half:top', 2 => 'open:true',],
    ],
    132 => [
        0 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        1 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        2 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        3 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        4 => [
            0 => 'attached:true',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        5 => [
            0 => 'attached:true',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        6 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        7 => [
            0 => 'attached:true',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        8 => [
            0 => 'attached:false',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        9 => [
            0 => 'attached:false',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        10 => [
            0 => 'attached:false',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        11 => [
            0 => 'attached:false',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        12 => [
            0 => 'attached:true',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        13 => [
            0 => 'attached:true',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
        14 => [
            0 => 'attached:false',
            1 => 'disarmed:false',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:false ',
        ],
        15 => [
            0 => 'attached:true',
            1 => 'disarmed:true',
            2 => 'north:false',
            3 => 'south:false',
            4 => 'east:false',
            5 => 'west:false',
            6 => 'powered:true ',
        ],
    ],
    131 => [
        0 => [0 => 'attached:false', 1 => 'facing:south', 2 => 'powered:false',],
        1 => [0 => 'attached:false', 1 => 'facing:west', 2 => 'powered:false',],
        2 => [0 => 'attached:false', 1 => 'facing:north', 2 => 'powered:false',],
        3 => [0 => 'attached:false', 1 => 'facing:east', 2 => 'powered:false',],
        4 => [0 => 'attached:true', 1 => 'facing:south', 2 => 'powered:false',],
        5 => [0 => 'attached:true', 1 => 'facing:west', 2 => 'powered:false',],
        6 => [0 => 'attached:true', 1 => 'facing:north', 2 => 'powered:false',],
        7 => [0 => 'attached:true', 1 => 'facing:east', 2 => 'powered:false',],
        8 => [0 => 'attached:false', 1 => 'facing:south', 2 => 'powered:true',],
        9 => [0 => 'attached:false', 1 => 'facing:west', 2 => 'powered:true',],
        10 => [0 => 'attached:false', 1 => 'facing:north', 2 => 'powered:true',],
        11 => [0 => 'attached:false', 1 => 'facing:east', 2 => 'powered:true',],
        12 => [0 => 'attached:true', 1 => 'facing:south', 2 => 'powered:true',],
        13 => [0 => 'attached:true', 1 => 'facing:west', 2 => 'powered:true',],
        14 => [0 => 'attached:true', 1 => 'facing:north', 2 => 'powered:true',],
        15 => [0 => 'attached:true', 1 => 'facing:north', 2 => 'powered:true',],
    ],
    106 => [
        0 => [
            0 => 'north:false',
            1 => 'south:false',
            2 => 'east:false',
            3 => 'west:false',
            4 => 'up:true ',
        ],
        1 => [0 => 'north:false', 1 => 'south:true', 2 => 'east:false', 3 => 'west:false', 4 => 'up:false',],
        2 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:true', 3 => 'west:false', 4 => 'up:false',],
        4 => [0 => 'north:true', 1 => 'south:false', 2 => 'east:false', 3 => 'west:false', 4 => 'up:false',],
        8 => [0 => 'north:false', 1 => 'south:false', 2 => 'east:true', 3 => 'west:false', 4 => 'up:false',],
    ],
    9 => [
        0 => [0 => 'level:0',],
        1 => [0 => 'level:1',],
        2 => [0 => 'level:2',],
        3 => [0 => 'level:3',],
        4 => [0 => 'level:4',],
        5 => [0 => 'level:5',],
        6 => [0 => 'level:6',],
        7 => [0 => 'level:7',],
        8 => [0 => 'level:8',],
        9 => [0 => 'level:9',],
        10 => [0 => 'level:10',],
        11 => [0 => 'level:11',],
        12 => [0 => 'level:12',],
        13 => [0 => 'level:13',],
        14 => [0 => 'level:14',],
        15 => [0 => 'level:15',],
    ],
    8 => [
        0 => [0 => 'level:0',],
        1 => [0 => 'level:1',],
        2 => [0 => 'level:2',],
        3 => [0 => 'level:3',],
        4 => [0 => 'level:4',],
        5 => [0 => 'level:5',],
        6 => [0 => 'level:6',],
        7 => [0 => 'level:7',],
        8 => [0 => 'level:8',],
        9 => [0 => 'level:9',],
        10 => [0 => 'level:10',],
        11 => [0 => 'level:11',],
        12 => [0 => 'level:12',],
        13 => [0 => 'level:13',],
        14 => [0 => 'level:14',],
        15 => [0 => 'level:15',],
    ],
    148 => [
        0 => [0 => 'power:0',],
        1 => [0 => 'power:1',],
        2 => [0 => 'power:2',],
        3 => [0 => 'power:3',],
        4 => [0 => 'power:4',],
        5 => [0 => 'power:5',],
        6 => [0 => 'power:6',],
        7 => [0 => 'power:7',],
        8 => [0 => 'power:8',],
        9 => [0 => 'power:9',],
        10 => [0 => 'power:10',],
        11 => [0 => 'power:11',],
        12 => [0 => 'power:12',],
        13 => [0 => 'power:13',],
        14 => [0 => 'power:14',],
        15 => [0 => 'power:15',],
    ],
    147 => [
        0 => [0 => 'power:0',],
        1 => [0 => 'power:1',],
        2 => [0 => 'power:2',],
        3 => [0 => 'power:3',],
        4 => [0 => 'power:4',],
        5 => [0 => 'power:5',],
        6 => [0 => 'power:6',],
        7 => [0 => 'power:7',],
        8 => [0 => 'power:8',],
        9 => [0 => 'power:9',],
        10 => [0 => 'power:10',],
        11 => [0 => 'power:11',],
        12 => [0 => 'power:12',],
        13 => [0 => 'power:13',],
        14 => [0 => 'power:14',],
        15 => [0 => 'power:15',],
    ],
    296 => [
        0 => [0 => 'age:0',],
        1 => [0 => 'age:1',],
        2 => [0 => 'age:2',],
        3 => [0 => 'age:3',],
        4 => [0 => 'age:4',],
        5 => [0 => 'age:5',],
        6 => [0 => 'age:6',],
        7 => [0 => 'age:7',],
    ],
    5 => [
        0 => [0 => 'variant:oak',],
        1 => [0 => 'variant:spruce',],
        2 => [0 => 'variant:birch',],
        3 => [0 => 'variant:jungle',],
        4 => [0 => 'variant:acacia',],
        5 => [0 => 'variant:dark_oak',],
    ],
];
